name: "astro -> gh pages"

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-page:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@latest
      - name: install + build + upload
        uses: withastro/action@latest
        with:
          path: ./web

  deploy:
    needs: build-page
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: deploy to gh pages
        id: deployment
        uses: actions/deploy-pages@latest
